name: My first flow

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
            - name: checkout actions
              uses: actions/checkout@v4

            - name: Multiple commands
              run: |
                echo "My first workflow"
                ls -lart
                cat README.md

            - name: generating ASCII
              run: cowsay -f dragon "Run for cover, I am gragon" >> dragon.txt
        

        


